paths:
  static: 'public'
  uploads: public/images

collections_config:
  pages:
    path: src/content/pages
    url: '/[full_slug]/'
    glob:
      - '**/*.md'
    icon: laptop_mac
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    schemas:
      default:
        name: New Page
        path: '.cloudcannon/schemas/page.md'
        remove_extra_inputs: false
    create:
      path: '[relative_base_path]/{filename|slugify}.md'
  posts:
    path: src/content/blog
    url: '/blog/[full_slug]/'
    glob:
      - '**/*.mdx'
    _enabled_editors:
      - content
      - visual
    add_options:
      - name: Add New Post
        schema: default
        icon: post_add
    schemas:
      default:
        name: New Post
        path: '.cloudcannon/schemas/post.mdx'
    create:
      path: '[relative_base_path]/{filename|slugify}.mdx'
    _inputs:
      title:
        options:
          empty_type: string
      image:
        options:
          empty_type: string
      image_alt:
        options:
          empty_type: string
      author:
        options:
          empty_type: string
      tags:
        type: array
        options:
          empty_type: array
      tags[*]:
        type: text
        options:
          empty_type: string
  data:
    path: data
    disable_url: true
    disable_add: true
    disable_add_folder: true
    _inputs:
      icons:
        comment: Add an icon from the list of [Font Awesome icons](https://fontawesome.com/search?o=r&m=free). Then add it to the ```src/components/utility/icon.jsx``` file, following the existing pattern.
      locales:
        type: array
        options:
          structures: _structures.locale
    _structures:
      locale:
        values:
          - value:
              code:
              name:
              flag:
            _inputs:
              name:
                comment: The text displayed in the language picker menu.
              code:
                comment: Enter the URL language code.
              flag:
                type: image
  translations:
    path: rosey
    icon: translate
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    glob:
      - config.yaml
      - 'translations/**'
    _inputs:
      urlTranslation:
        type: text
        comment: Provide a translation for the URL that Rosey will build this page at.

collection_groups:
  - heading: Pages
    collections:
      - pages
      - posts
  - heading: Data
    collections:
      - data
      - translations
      - translations_config

file_config:
  - glob: data/colors.json
    _structures:
      color:
        values:
          - value:
              name:
              value:
            preview:
              icon: palette
    _inputs:
      $:
        type: array
        label: Colors
        comment: Set the colors available in the color selectors throughout the site.
        options:
          structures: _structures.color
      value:
        type: color
      name:
        type: text
        comment: What is seen in the color selector dropdown.

data_config:
  icons:
    path: data/icons.json
  colors:
    path: data/colors.json
 
_editables:
  content: &markdown_options
    bold: true
    format: p h1 h2 h3 h4
    italic: true
    link: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    bulletedlist: true
    numberedlist: true
    blockquote: true
    superscript: true
    subscript: true
    code: true
    horizontalrule: true
    image: true
    snippet: true

_inputs:
  image_path:
    type: image
    comment: The path to the source file of the image to be optimized.
    options:
      accepts_mime_types:
        - image/png
        - image/jpeg
        - image/gif
      paths:
        static: '.'
        uploads: src/assets/images
  alt_text:
    label: Image Alt Text
    type: textarea
    hidden: '!image_path'
  width:
    type: number
  height:
    type: number
  background_color:
    hidden: 'border_only'
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  icon:
    type: select
    options:
      values: data.icons
  button_icon:
    type: select
    options:
      values: data.icons
  button_link:
    type: url
  hover_brightness:
    type: range
    options:
      min: 0
      max: 1.5
      step: 0.05
  seo:
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  layout:
    hidden: true
  date:
    instance_value: NOW
  page_size:
    type: number
    comment: The number of collection items to list per page
  social:
    options:
      preview:
        icon: link
  links[*]:
    options:
      preview:
        icon: link
        text:
          - key: text
          - 'Link'
        subtext:
          - key: link
          - 'Add a social link'
  social_icon:
    type: select
    options:
      values: data.icons
  social[*]:
    options:
      preview:
        icon: query_stats
  logo:
    type: image
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    type: select
    options:
      values:
        - website
        - article
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  twitter_site:
    type: url
  no_index:
    type: checkbox
    comment:
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag

_snippets_imports:
  mdx: true
_snippets:
  alert:
    template: mdx_component
    inline: false
    preview:
      text:
        - key: alert_message
        - 'Alert'
    definitions:
      component_name: SnippetsAlert
      named_args:
        - editor_key: background_color
          source_key: background_color
          type: string
        - editor_key: alert_message
          source_key: alert_message
          type: string
        - editor_key: color
          source_key: color
          type: string
        - editor_key: icon
          source_key: icon
          type: string
    _inputs:
      background_color:
        type: select
        options:
          values: data.colors
          value_key: value
          preview:
            text:
              - key: name
      icon:
        type: select
        options:
          values: data.icons
      color:
        type: select
        options:
          values: data.colors
          value_key: value
          preview:
            text:
              - key: name
      alert_message:
        comment: This is the text displayed in the alert
        type: textarea
  video:
    template: mdx_component
    inline: false
    preview:
      text: Video
    definitions:
      component_name: SnippetsVideo
      named_args:
        - editor_key: src
          source_key: src
          type: string
    _inputs:
      src:
        type: file
        options:
          paths:
            uploads: public/videos
  file:
    template: mdx_component
    inline: false
    preview:
      text: File
    definitions:
      component_name: SnippetsFile
      named_args:
        - editor_key: src
          source_key: src
          type: string
        - editor_key: file_name
          source_key: file_name
          type: string
        - editor_key: link_message
          source_key: link_message
          type: string
    _inputs:
      src:
        type: file
        label: File source
        options:
          paths:
            uploads: public/documents
      file_name:
        comment: The name of the file, once downloaded.
      link_message:
        type: textarea
        comment: The text for the download link
  mdx_tint:
    template: mdx_paired_component
    inline: true
    preview:
      text: Tint
    definitions:
      component_name: SnippetsTint
      content_key: inner_text
      named_args:
        - editor_key: color
          source_key: tint_color
          type: string
    _inputs:
      tint_color:
        type: color
      inner_text:
        comment: This text will be tinted
