source: jekyll

timezone: Etc/UTC

paths:
  uploads: site/images
  static: 'site'
  
collections_config:
  posts:
    path: site/collections/_posts
    url: '/[full_slug]/'
    glob:
      - '**/*.md'
    icon: newspaper
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: jekyll/.cloudcannon/schemas/post.md
  pages:
    path: site/collections/_pages
    url: '/[full_slug]/'
    glob:
      - '**/*.html'
    icon: laptop_mac
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: jekyll/.cloudcannon/schemas/page.html
    create:
      path: '[relative_base_path]/{filename|slugify}.md'
  projects:
    path: site/collections/_projects
    url: '/[full_slug]/'
    glob:
      - '**/*.md'
    description: ''
    icon: work_outline
    preview:
      subtext:
        - key: subtitle
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: jekyll/.cloudcannon/schemas/project.md
    create:
      path: '[relative_base_path]/{filename|slugify}.md'
  testimonials:
    path: site/collections/_testimonials
    url: '/[full_slug]/'
    glob:
      - '**/*.md'
    description: ''
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    preview:
      subtext:
        - key: position
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: jekyll/.cloudcannon/schemas/testimonial.md
    create:
      path: '[relative_base_path]/{filename|slugify}.md'
  drafts:
    path: site/collections/_drafts
    disable_url: true
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: site/_data
    disable_url: true
    disable_add: true
    disable_add_folder: true
    _inputs:
      icons:
        comment: Add an icon from the list of [Font Awesome icons](https://fontawesome.com/search?o=r&m=free). Then add it to the ```src/components/utility/icon.jsx``` file, following the existing pattern.
      locales:
        type: array
        options:
          structures: _structures.locale
    _structures:
      locale:
        values:
          - value:
              code:
              name:
              flag:
            _inputs:
              name:
                comment: The text displayed in the language picker menu.
              code:
                comment: Enter the URL language code.
              flag:
                type: image
  translations:
    path: rosey
    icon: translate
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    glob:
      - config.yaml
      - 'translations/**'
    _inputs:
      urlTranslation:
        type: text
        comment: Provide a translation for the URL that Rosey will build this page at.

collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
      - translations
    
data_config:
  author:
    path: site/_data/author.yml
  footer:
    path: site/_data/footer.yml
  general_settings:
    path: site/_data/general_settings.yml
  navigation:
    path: site/_data/navigation.yml
  newsletter:
    path: site/_data/newsletter.yml
  social_links:
    path: site/_data/social_links.yml

_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
