# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonials
  description: Testimonials Section with heading, a description and a link
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  show_testimonials: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Happy Clients
  description_html: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
