# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left Right
  description: Text next to image with button
  icon: "chrome_reader_mode"
  tags:
    - Text
    - Image
    - Button
    - Flippable

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#ffffff"
  heading:
    heading_text:
    color: "#393939"
  text:
    markdown_content:
    color: "#393939"
  media:
    image_path: /src/assets/images/undraw-hello.svg
    youtube_path:
    alt_text: An image
  flipped: true
  button: bookshop:structure:buttons

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  markdown_content:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  heading_text:
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  heading:
    options:
      preview:
        icon: "short_text"
        text:
          - key: heading_text.original
          - Heading
        subtext:
          - key: heading_gradient_color
          - "Update heading gradient color and text content."
  text:
    options:
      preview:
        icon: "edit_note"
        text:
          - Text
        subtext:
          - "Update text content and color."
  media:
    options:
      preview:
        icon: "image"
        text:
          - key: alt_text
          - "Image"
        subtext:
          - key: image_path
          - key: youtube_path
          - "Update image or video"
        image:
          - key: image_path
  youtube_path:
    type: file
  flipped:
    type: switch
