# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Project Card
  description: Project card used for project lists
  icon: wysiwyg
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  project:
    title: ""
    subtitle: ""
    image: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  project:
    title: Hello World
    subtitle: Lorem Ipsum
    image: https://placekitten.com/800/400
    url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
